version: "3.4"
services:
  server:
    image: server
    build:
      context: ./server/RestADServer4
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  client:
    image: client
    build:
      context: ./client/client-app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    links:
      - server
    depends_on:
      - server