version: "3.4"
services:
  server:
    image: server
    build:
      context: ./server/RestADServer4
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db
  client:
    image: client
    build:
      context: ./client/client-app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    links:
      - server
    depends_on:
      - server
  db:
    image: db
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - ./db/sqlserver.env
    ports:
      - 1527:1527